server:
  compression:
    enabled: true
    min-response-size: 1
  connection-timeout: 5000
  port: 8088

management:
  security:
    enabled: false

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pay_back?autoReconnect=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    minIdle: 1
    maxActive: 10
    maxWait: 10000
    timeBetweenEvictionRunsMillis: 6000
    minEvictableIdleTimeMillis: 300000
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    defaultAutoCommit: true
    validationQuery: select 1
    filters: stat
  redis:
    database: 2
    host: 127.0.0.1
    prot: 6379
    timeout: 3000ms

swagger:
  enable: true
  base-package: com.oceanus.pay

mybatis:
  mapper-locations: classpath*:mapper/*.xml

